apiVersion: v1
kind: Namespace
metadata:
  name: agion-langgraph
  labels:
    name: agion-langgraph
    app: langgraph-agents
    platform.agion.com/component: agent-container
    platform.agion.com/zone: compute
